### PR TITLE
Add dynamic reconfigure for ds_second_peak_threshold

### PR DESCRIPTION
**Pull request by philip-at-greenzie**
This PR adds ds_second_peak_threshold to dynamic_reconfigure.

This will allow us to compare performance with different values.

### CODE REVIEW

**Review by AGummyBear — COMMENTED** [review]
The code looks foreign to me, but I'm assuming this is related to how you said they do dynamic reconfigure in their own way.

We will need to make sure the package version is bumped in some manner, so that this gets deployed and updated appropriately. @orensbruli may be able to help here.

**Comment by philip-at-greenzie** [comment]
Thanks @AGummyBear. Good point about the version number. I see in debian/changelog that in the past we have appended an index as we made versions ex(102.2.22-bionic1, 102.2.22-bionic2, 102.2.22-bionic3). Our current version is 2.3.2-greenzie-focal, so maybe we bump to 2.3.2-greenzie-focal2. This packaging and deployment is new to me, so I'm not confident or even sure what is controlling the package version string or how to change it. @orensbruli any help or suggestions would be most welcome.

**Review by btdubs — APPROVED** [review]

**Comment by AGummyBear** [comment]
Going to `focal2` should be sufficient. Just copy and paste the previous entry and change the version (and date, if there is one).  We can verify after CI builds the debs that the version has changed

**Comment by philip-at-greenzie** [comment]
It the filename of the deb does now have the bumped version(2.3.2-greenzie-focal2)

I had no idea that the packager was parsing the changelog. Good to know!

https://app.circleci.com/pipelines/github/Greenzie/realsense-ros/5/workflows/2cfa4c3f-c861-4067-a37d-4647f9ab9c9b/jobs/7/artifacts

**Review by AGummyBear — APPROVED** [review]

**Comment by philip-at-greenzie** [comment]
Does merging this into noetic deploy the change?

**Comment by AGummyBear** [comment]
> Does merging this into noetic deploy the change?

It should, if the CI is working as intended.

**Pull request merged**
